server:
  port: 8086


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:qiaolezi}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: com.smart.store.config.MyDialect
logging:
  level:
    root: info
